title: Emmanuel Obawole
logo: Photo.jpg
description: I am a data analyst with 2 years of experience working across various sectors, turning raw data into strategic insights. I specialize in using advanced Excel (including VBA macros) for report automation, SSIS (SQL) for data interrogation and transformation, and Power BI to deliver impactful business intelligence reports. My work empowers teams to make smarter, data-backed decisions efficiently.
#show_downloads: true 
#google analytics:
theme: jekyll-theme-minimal
